### ISSUE TITLE
 No module named 'graphql.language'; 'graphql' is not a package

### ISSUE THREAD

**Issue by mohendra** [seermedical/seer-py#13]
While I tried to import the import seerpy module the following error apeard.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-9ba33c122bf8> in <module>()
----> 1 import seerpy
      2 from seerpy.plotting import seerPlot

~\Downloads\seer-py-0.1.1-beta\seer-py-0.1.1-beta\seerpy\seerpy.py in <module>()
      1 # Copyright 2017 Seer Medical Pty Ltd, Inc. or its affiliates. All Rights Reserved.
----> 2 from gql import gql, Client as GQLClient
      3 from gql.transport.requests import RequestsHTTPTransport
      4 import numpy as np
      5 import pandas as pd

~\Anaconda3\lib\site-packages\gql\__init__.py in <module>()
----> 1 from .gql import gql
      2 from .client import Client
      3 
      4 __all__ = ['gql', 'Client']

~\Anaconda3\lib\site-packages\gql\gql.py in <module>()
      1 import six
----> 2 from graphql.language.parser import parse
      3 from graphql.language.source import Source
      4 
      5 

ModuleNotFoundError: No module named 'graphql.language'; 'graphql' is not a packag

**Comment by sumaiyas** [comment]
I have the same issue. Can anyone help?

**Comment by bjdoyle** [comment]
Hi @mohendra and @sumaiyas, sorry for the delayed response. We have released a new version https://github.com/seermedical/seer-py/releases/tag/v0.2.1, can you please download the latest version and see if you still have the same issue?

**Comment by sumaiyas** [comment]
Thank you @bjdoyle for your response, but it has since been resolved.

**Comment by YasminAMassoud** [comment]
@mohendra @sumaiyas @bjdoyle I  am having the same issue can you please advice how to solve it ?

**Comment by bjdoyle** [comment]
Hi @YasminAMassoud you need to install the seerpy package using one of the Python install utilities like pip or conda.

**Comment by YasminAMassoud** [comment]
lled

**Comment by YasminAMassoud** [comment]
@bjdoyle  I am still having the same iss of graphgql error 
- I have pip and pythn working using anaconda 
-requirements.txt installed 
However running pip install seerpy and python seerpy.py install doesnt work

**Comment by bjdoyle** [comment]
Hi @YasminAMassoud from the seer-py directory (at the level which contains requirements.txt and setup.py) you should run
`pip install -r requirements.txt` or `pip install .`
This will install seerpy and all of it's requirements.
Alternatively, from the same directory you can run
`python setup.py install`
which will do the same.
Just a caution with the setup.py method that when I just tried it it installed version 3.0.0b1 of graphql-core which didn't seem to be compatible with the 0.1.0 version of gql also installed.
