### ISSUE TITLE
Feature Request: Limit max items returned in paginated query

### ISSUE THREAD

**Issue by ronrest** [seermedical/seer-py#130]
https://github.com/seermedical/seer-py/blob/ec2599f0392f277c5bbf1b2643104e0b9dc06725/seerpy/seerpy.py#L158

Can I suggest that we add a parameter to the `client.get_paginated_response()` that limits the total amount of items that it returns? Currently we have `limit` which limits the amount of items returned per page in the paginated request. But nothing to limit the total number of items returned. 

I am happy to implement this. I just want to get peoples input on this idea, and what the argument should be called. Can I suggest calling it `max_items`?

**NOTE:** for queries such as the following, which contain nested lists of items, the `max_items` would only affect the outer list (2 `users`, irrespective of how many `surveys` for those users).

```
query userSurveysLimit{
  users(offset: 82, limit:2){
    username
    surveys{
        id
    }
  }
}
```

**Where it is useful**

When getting studies, we currently have `client.get_studies()` which gets ALL studies that the user has access to. If a user or developer is just experimenting, they may not want to wait around for 10 or more minutes to get ALL studies. Its an unpleasant experience.

**Upstream changes**

If this idea is accepted, I suggest also adding the same arguments to all other functions that call `get_paginated_response`, such as `get_studies()` `get_studies_dataframe()`, etc.

I am happy to implement this as well.

Besides the functions in `seerpy.py` are there any other calls to `client.get_paginated_response()` that i should know about?

**Comment by norrishd** [comment]
Wow can I not agree strongly enough.

A related suggestion/proposal: We shouldn't even expose query page size as a method parameter; it should be an implementation detail that we optimise and set at the function level.

While we're talking query efficiency, it may also be worth updating some/all (?) of the queries to use the new resources schema - @cheewee-seer and @jenniferanneaus might have input on this.

**Comment by ronrest** [comment]
> A related suggestion/proposal: We shouldn't even expose query page size as a method parameter; it should be an implementation detail that we optimise and set at the function level.

So do you mean removing the current `limit` argument from functions? And just have it as an attribute within the `SeerConnect` object?

**Comment by dkeden** [comment]
Yes, absolutely from me too. I would agree that it's a very unpleasant experience! Also agree w/ suggestion made by @norrishd.

Not any other calls to `client.get_paginated_response()` outside of `seerpy.py` from the research team at least.

**Comment by ronrest** [comment]
> While we're talking query efficiency, it may also be worth updating some/all (?) of the queries to use the new resources schema - @cheewee-seer and @jenniferanneaus might have input on this.

I would be quite happy to help with porting some of the python code to make use of the new resource schema. 


Can I suggest you open up two separate Git Issues for these two suggestions you made, so each one can be treated individually? That way we don't end up with a lot of cross talk on the one Git Issue.

**Comment by EwanNurse** [comment]
> Yes, absolutely from me too. I would agree that it's a very unpleasant experience! Equally true for, e.g. `get_patients()`. Also agree w/ suggestion made by @norrishd.
> 
> Not any other calls to `client.get_paginated_response()` outside of `seerpy.py` from the research team at least. The algo team would be the only other to check with?

Sorry I'm late to the party, using some _very_ questionable/naïve methods I [can't see it being called in the seer-algo repo]
(https://github.com/seermedical/seer-algo/search?q=get_paginated_response)
