### ISSUE TITLE
Empatica Accelerometery data the same for all channels

### ISSUE THREAD

**Issue by baileystimac** [seermedical/seer-py#146]
I used the msg_data_downloader.pyscript to download the data and have found that the Empatica accelerometery data is exactly the same across all channels for each patient. Not sure if this is a user error or an issue with the script??

**Comment by EwanNurse** [comment]
Hi baileystimac ,

Thanks for getting in touch. We're looking in to this issue now, and can hopefully get back to you with a fix in the near future.

Regards,
Ewan

**Comment by baileystimac** [comment]
I don't know if this is a separate or related issue but there are also multiple data entries for some time values in the accelerometery data.

**Comment by EwanNurse** [comment]
Hi there,

The data for each channel in the accelerometer channel group should now be correct, thanks for bringing it to our attention! We're looking into the timestamp issue as well.

Regards,
Ewan

**Comment by baileystimac** [comment]
Thanks Ewan!
