### ISSUE TITLE
Error pulling data

### ISSUE THREAD

**Issue by JaydenDad** [seermedical/seer-py#20]
Hello Levin,

I was trying to download the contest data from seer and got the following issue. Could you please help me with it?
<img width="876" alt="Capture" src="https://user-images.githubusercontent.com/52357790/63069479-fbedd700-bee4-11e9-8738-25411110e7e4.PNG">
Thanks a lot!

**Comment by bjdoyle** [comment]
Hi @JaydenDad it looks like you must have an old version of seer-py installed but are using a new version of contest_data_downloader.py.
Let me know if you need any help to sort that out.

**Comment by JaydenDad** [comment]
Hi @bjfoyle,

Thx for your reply but I think it's not the case. I have updated my seer-py before seeing this issue. But I didn't use the latest gql. Could it be the reason?

**Comment by bjdoyle** [comment]
I think you have an older version of seerpy in your installed libraries, but are using the script from the new version. You need to make sure you have `pip install`ed the new version so that the script will pick it up. The method it says is not on SeerConnect is on the latest version.
