### ISSUE TITLE
No module named seerpy

### ISSUE THREAD

**Issue by YasminAMassoud** [seermedical/seer-py#26]
### I get this error when i run the example 

```
_**> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-07d729194a8a> in <module>
>       8 from scipy.io import savemat  # pylint: disable=unused-import
>       9 
> ---> 10 import seerpy
>      11 
>      12 
> 
> ModuleNotFoundError: No module named 'seerpy'**_
```

I downloaded the lastest version of seerpy repository

**Comment by bjdoyle** [comment]
Hi @YasminAMassoud you need to install the seerpy package using one of the Python install utilities like pip or conda.

**Comment by YasminAMassoud** [comment]
Hi @bjdoyle thanks for ur reply 
I tried pip install seer-py 
and pip install seerpy in my command window with no joy

**Comment by bjdoyle** [comment]
Hi @YasminAMassoud from the seer-py directory (at the level which contains requirements.txt and setup.py) you should run
`pip install -r requirements.txt`
This will install seerpy and all of it's requirements.
Alternatively, from the same directory you can run
`python setup.py install`
which will do the same.
Just a caution with the setup.py method that when I just tried it it installed version 3.0.0b1 of graphql-core which didn't seem to be compatible with the 0.1.0 version of gel also installed.

**Comment by YasminAMassoud** [comment]
I still get the same error  :this what i get when i run pip install -r requirements.txt from seerpy directory

> `
C:\seer-py-0.2.1\seer-py-0.2.1>pip install -r requirements.txt
Requirement already satisfied: gql in c:\users\jasmin\appdata\local\programs\pyt
hon\python37\lib\site-packages (from -r requirements.txt (line 1)) (0.1.0)
Requirement already satisfied: requests in c:\users\jasmin\appdata\local\program
s\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (2.22.0)

Requirement already satisfied: matplotlib in c:\users\jasmin\appdata\local\progr
ams\python\python37\lib\site-packages (from -r requirements.txt (line 3)) (3.1.1
)
Requirement already satisfied: numpy in c:\users\jasmin\appdata\local\programs\p
ython\python37\lib\site-packages (from -r requirements.txt (line 4)) (1.17.2)
Requirement already satisfied: pandas in c:\users\jasmin\appdata\local\programs\
python\python37\lib\site-packages (from -r requirements.txt (line 5)) (0.25.1)
Requirement already satisfied: H5py in c:\users\jasmin\appdata\local\programs\py
thon\python37\lib\site-packages (from -r requirements.txt (line 6)) (2.10.0)
Requirement already satisfied: six>=1.10.0 in c:\users\jasmin\appdata\local\prog
rams\python\python37\lib\site-packages (from gql->-r requirements.txt (line 1))
(1.12.0)
Requirement already satisfied: graphql-core>=0.5.0 in c:\users\jasmin\appdata\lo
cal\programs\python\python37\lib\site-packages (from gql->-r requirements.txt (l
ine 1)) (2.2.1)
Requirement already satisfied: promise>=0.4.0 in c:\users\jasmin\appdata\local\p
rograms\python\python37\lib\site-packages (from gql->-r requirements.txt (line 1
)) (2.2.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\use
rs\jasmin\appdata\local\programs\python\python37\lib\site-packages (from request
s->-r requirements.txt (line 2)) (1.25.6)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\jasmin\appdata\local\p
rograms\python\python37\lib\site-packages (from requests->-r requirements.txt (l
ine 2)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jasmin\appdata\loc
al\programs\python\python37\lib\site-packages (from requests->-r requirements.tx
t (line 2)) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\jasmin\appdata\
local\programs\python\python37\lib\site-packages (from requests->-r requirements
.txt (line 2)) (3.0.4)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\us
ers\jasmin\appdata\local\programs\python\python37\lib\site-packages (from matplo
tlib->-r requirements.txt (line 3)) (2.4.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\jasmin\appdata\loca
l\programs\python\python37\lib\site-packages (from matplotlib->-r requirements.t
xt (line 3)) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\jasmin\appdata\local\pro
grams\python\python37\lib\site-packages (from matplotlib->-r requirements.txt (l
ine 3)) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\jasmin\appdata\l
ocal\programs\python\python37\lib\site-packages (from matplotlib->-r requirement
s.txt (line 3)) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\jasmin\appdata\local\pro
grams\python\python37\lib\site-packages (from pandas->-r requirements.txt (line
5)) (2019.3)
Requirement already satisfied: rx<3,>=1.6 in c:\users\jasmin\appdata\local\progr
ams\python\python37\lib\site-packages (from graphql-core>=0.5.0->gql->-r require
ments.txt (line 1)) (1.6.1)
Requirement already satisfied: setuptools in c:\users\jasmin\appdata\local\progr
ams\python\python37\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->-r re
quirements.txt (line 3)) (40.8.0)

C:\seer-py-0.2.1\seer-py-0.2.1>

Can you please help with this problem ?Thanks alot

**Comment by bjdoyle** [comment]
Hi @YasminAMassoud what version of Python are you using?
And what are you doing when you get the error?
Are you trying to run contest_data_downloader from the command line or in an interpreter or importing it into another module?

**Comment by YasminAMassoud** [comment]
@bjdoyle 
Python 3.7.4
pip 19.2.3
I use anaconda3 then open jupyter notebook and i run the contest_data_downloader: 
Python 3.7.4
pip 19.2.3

**Comment by bjdoyle** [comment]
Hi @YasminAMassoud can you run `help('modules')` in your jupyter notebook and confirm that seerpy is listed in the available modules?

**Comment by YasminAMassoud** [comment]
Hi @bjdoyle  and thanx for your patience, no its not there

**Comment by bjdoyle** [comment]
No worries @YasminAMassoud. It seems your Jupyter notebook is not running in the same conda environment in which you have installed seerpy. You need to start Jupiter from the correct conda environment, or create the correct environment in Jupyter.

**Comment by YasminAMassoud** [comment]
I solved the issue by making python work using anaconda by adding python.exe location from anaconda folder in env. variables(path). then ran the contest_data_downloader using cmd .
