### ISSUE TITLE
ValueError: cannot reshape array of size 58 into shape (16,400)

### ISSUE THREAD

**Issue by YasminAMassoud** [seermedical/seer-py#37]
I get this error when i download file 160 in Test Files for Partient 3 ,Can anyone help ?

**Comment by bjdoyle** [comment]
Hi @YasminAMassoud we had a problem with the API overnight, but it should be fine now. Please try again and let me know if you still have problems.

**Comment by YasminAMassoud** [comment]
I confirm its working now, thanks .
